cd /Users/shohei/work/NBA/Evaluation
python link_prediction_appeared.py
python link_prediction_disappeared.py
python attribute_prediction_exist_Age.py
python attribute_prediction_exist_Pos.py
python attribute_prediction_exist_PTS.py
python attribute_prediction_exist_Tm.py
python attribute_prediction_exist_Tm_binary.py